name: My Workflow

on: 
    push: 
        branches: 
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Show files
              run: ls
            
            - name: Run node file
              run: node index.js

            - name: Print Current Directory
              run: pwd

            - name: Say Hello
              run: echo "Someone's is learning devOps, Let's GO!!"